### ISSUE TITLE
DLM/CLVM can't rejoin cluster

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#142] opened 2015-08-29 10:05 UTC
Hi, I have problem with putting one node to standby and then back online. CLVM cant start because it cant join cluster using sctp.

Here is kernel log

	Aug 29 11:57:06 storage2 kernel: [ 1100.762289] dlm: Trying to connect to 192.168.2.40
	Aug 29 11:57:06 storage2 kernel: [ 1100.762413] dlm: Can't start SCTP association - retrying
	Aug 29 11:57:06 storage2 kernel: [ 1100.762418] dlm: Retry sending 64 bytes to node id 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762423] dlm: Retrying SCTP association init for node 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762423] 
	Aug 29 11:57:06 storage2 kernel: [ 1100.762428] dlm: Trying to connect to 192.168.10.1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762628] dlm: Can't start SCTP association - retrying
	Aug 29 11:57:06 storage2 kernel: [ 1100.762632] dlm: Retry sending 64 bytes to node id 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762637] dlm: Retrying SCTP association init for node 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762637] 
	Aug 29 11:57:06 storage2 kernel: [ 1100.762641] dlm: Trying to connect to 192.168.2.40
	Aug 29 11:57:06 storage2 kernel: [ 1100.762723] dlm: Can't start SCTP association - retrying
	Aug 29 11:57:06 storage2 kernel: [ 1100.762726] dlm: Retry sending 64 bytes to node id 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762730] dlm: Retrying SCTP association init for node 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762730] 
	Aug 29 11:57:06 storage2 kernel: [ 1100.762735] dlm: Trying to connect to 192.168.10.1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762916] dlm: Can't start SCTP association - retrying
	Aug 29 11:57:06 storage2 kernel: [ 1100.762922] dlm: Retry sending 64 bytes to node id 1
	Aug 29 11:57:06 storage2 kernel: [ 1100.762929] dlm: Retrying SCTP association init for node 1

I found this patch http://www.redhat.com/archives/linux-cluster/2014-June/msg00017.html

**Comment by feldsam** [comment] 2015-08-29 10:09
Node is fenced, but after restart can't rejoin cluster too, I need to restart clvmd/dlm on alive node, so put whole cluster down :(

**Comment by msmith626** [comment] 2015-08-29 13:47
That's a bummer, looks like they aren't back-porting that patch into kernels (its not in 3.14.51, least in 3.14.x).

I'd prefer to just update to the latest in 3.14 but since that isn't an option, we have the following choices:
- In master, update the Linux kernel to a new version (something I've been wanting to do, waiting for 4.2).
- Or create a one-off patch for 3.14.36 and apply to both branches.

What are your thoughts, preference?


--Marc

**Comment by feldsam** [comment] 2015-08-29 16:23
Hi, I am looking to 4.2-rc8 sources and it's patched. I don't know, what is better?

**Comment by msmith626** [comment] 2015-08-29 16:25
I want to move master to the latest kernel, but 0.1.x will stay at 3.14. I
guess the question is, will this affect 0.1.x users as well, or is this
something specific only reproducible with the master branch? If its both,
then its probably best to patch 3.14 for now.

On Sat, Aug 29, 2015 at 12:23 PM, Kristian Feldsam <notifications@github.com

**Comment by feldsam** [comment] 2015-08-29 16:26
I experience issues with clvm on older releases too, so patch

**Comment by msmith626** [comment] 2015-08-29 16:29
Okay, I'll have this done shortly.

--Marc

On Sat, Aug 29, 2015 at 12:26 PM, Kristian Feldsam <notifications@github.com

**Comment by feldsam** [comment] 2015-08-29 19:11
What about this? I can create path right now for you.

**Comment by feldsam** [comment] 2015-08-29 19:23
It's ok?

**Comment by msmith626** [comment] 2015-08-29 19:51
Yes, merged, thanks.

**Closed by msmith626** 2015-08-29 19:51 UTC
Labels: bug
