### ISSUE TITLE
perfagent does not work

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#110] opened 2015-04-13 20:11 UTC
Attempting to start it per the wiki instructions:

[root@esos1 ~]# /etc/rc.d/rc.perfagent start
Traceback (most recent call last):
  File "/etc/rc.d/rc.perfagent", line 13, in <module>
    from daemon import runner
ImportError: No module named daemon

**Comment by msmith626** [comment] 2015-04-15 01:14
I tried this myself and don't get the exact same error message, but I believe I know what the culprit is. Is your ESOS one you built from source, a "vanilla" ESOS package?

--Marc

**Comment by dswartz** [comment] 2015-04-15 01:28
On 2015-04-14 21:14, Marc A. Smith wrote:
> I tried this myself and don't get the exact same error message, but I
> believe I know what the culprit is. Is your ESOS one you built from
> source, a "vanilla" ESOS package?

No, it's a vanilla 0.1.1 zipfile off the DL site...

**Comment by msmith626** [comment] 2015-04-18 14:32
Okay, I finally had some time to get to this; I got it fixed in master... the root cause was the Buildbot that builds the packages uses parallel make and the Python module targets were clobbering each other and didn't install correctly. I added dependency rules so all Python module targets are serialized.

This fixes the Python import error messages, but after looking at the perfagent daemon code, its pretty weak. I didn't actually write this myself, another contributor did some years back. I've never used it personally, and after playing with it a bit for this, well, it needs a lot of work. Its hard to understand if something is mis-configured when using it as it relies on print statements, yet stdout/stderr are redirected to /dev/null. It should use syslog so we can understand that's going on, among other things.

Know Python? Interested in working on it? I would, and I plan to in the future, but I have so much on my plate right now, its really low priority.

Anyhow, if you want to try it out with the latest package from the master branch, and confirm it works, I'll merge that fix into 0.1.x.

--Marc

**Comment by dswartz** [comment] 2015-04-18 15:00
On 2015-04-18 10:32, Marc A. Smith wrote:
> Okay, I finally had some time to get to this; I got it fixed in
> master... the root cause was the Buildbot that builds the packages
> uses parallel make and the Python module targets were clobbering each
> other and didn't install correctly. I added dependency rules so all
> Python module targets are serialized.
> 
> This fixes the Python import error messages, but after looking at the
> perfagent daemon code, its pretty weak. I didn't actually write this
> myself, another contributor did some years back. I've never used it
> personally, and after playing with it a bit for this, well, it needs a
> lot of work. Its hard to understand if something is mis-configured
> when using it as it relies on print statements, yet stdout/stderr are
> redirected to /dev/null. It should use syslog so we can understand
> that's going on, among other things.
> 
> Know Python? Interested in working on it? I would, and I plan to in
> the future, but I have so much on my plate right now, its really low
> priority.
> 
> Anyhow, if you want to try it out with the latest package from the
> master branch, and confirm it works, I'll merge that fix into 0.1.x.

I'll give this a try soon.  Unfortunately, I can spell 'python' but 
that's pretty much the extent :)  Is there any kind of tool to pull and 
display the accumulated data from the DB?  I'm in the process of 
switching from mdraid to zfs for my SOHO rig - hopefully performance 
numbers later...

**Comment by msmith626** [comment] 2015-04-18 15:02
We have the start of a tool for viewing the performance statistics from a database, so that is in the works, and the plan was to revamp the perfagent script when we get further with the viewing tool.

So, maybe hold off until later this summer, and we'll have the perfagent stuff working a bit better. =)


--Marc

**Closed** 2015-05-08 20:46 UTC
Labels: bug
